name: NMBUSC Copy API/REST/contexts to https://nmbu-campus.github.io

on:
  workflow_dispatch:
  push:
    branches: 
      - "university_dev"
    paths:
      - "API/REST/contexts/**"

jobs:
  copy-contexts-to-github-io-site:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token:  ${{ secrets.CI_PUSH_PAT }}
    - name: Set short git commit SHA
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
    - name: 'Checkout dev site'
      uses: actions/checkout@v6
      with:
        repository: NMBU-Campus/nmbu-campus.github.io
        path: nmbu-campus.github.io
        token:  ${{ secrets.CI_PUSH_PAT }}
    - name: 'Delete contexts from dev site'
      run: rm -rf ./nmbu-campus.github.io/contexts/*
    - name: 'Copy new contexts to dev site'
      run: cp -r ./API/REST/contexts/* ./nmbu-campus.github.io/contexts/
    - name: 'Commit and push updated contexts'
      run: |
        cd ./nmbu-campus.github.io/contexts/
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions[bot]"
        git add . 
        git commit -a -m "Updated contexts for sha ${{ env.COMMIT_SHORT_SHA }}"
        git push
